name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts

#      - name: Remove conflicting packages
#        run: |
#          sudo apt-get remove -y containerd
#          sudo apt-get clean
#          sudo apt-get update
#          sudo apt-get autoremove -y
#          sudo apt-get install -y containerd.io

      - name: Build and push Docker image
        run: |
          docker build -t jadidlar-front .
          echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u userhubdocker1 --password-stdin
          docker tag jadidlar-front userhubdocker1/jadidlar-front
          docker push userhubdocker1/jadidlar-front
          

      - name: Disable strict host key checking
        run: echo "StrictHostKeyChecking no" >> ~/.ssh/config

      - name: SSH into server and deploy
        run: |
          ssh root@93.188.84.132 'docker pull userhubdocker1/jadidlar-front && docker run -d -p 5200:5200 userhubdocker1/jadidlar-front'
