name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to DockerHub
        env:
          DOCKERHUB_USERNAME: userhubdocker1
          DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
        run: |
          echo "$DOCKERHUB_TOKEN" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin

      - name: Build and push Docker image
        run: |
          docker build -t jadidlar-front .
          docker tag jadidlar-front userhubdocker1/jadidlar-front
          docker push userhubdocker1/jadidlar-front

      - name: Disable strict host key checking
        run: echo "StrictHostKeyChecking no" >> ~/.ssh/config

      - name: SSH into server and deploy
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh root@93.188.84.132 << EOF
            docker pull userhubdocker1/jadidlar-front
            docker stop jadidlar-container || true
            docker rm jadidlar-container || true
            docker run --name jadidlar-container -d -p 5200:5200 userhubdocker1/jadidlar-front
          EOF
